#!/usr/bin/with-contenv bash
export CRONICLE_foreground=1
export CRONICLE_echo=1
export CRONICLE_web_socket_use_hostnames=1
export CRONICLE_server_comm_use_hostnames=1
export CRONICLE_web_direct_connect=0

if [ ! -d "/opt/cronicle/data" ]; then
    /opt/cronicle/bin/control.sh setup
fi

/opt/cronicle/bin/control.sh start
