#!/usr/bin/with-contenv bash
su $USER -c 'cd ~ && \
export SHELL=/bin/bash && \
cat /etc/profile > ~/.bashrc && \
/usr/local/bin/code-server --auth none --disable-telemetry "$HOME" --bind-addr 0.0.0.0:8080'
